# Numpy Practice Jupyter Notebook

In [1]:
# Create a python list

a = ["0", 1, "two", "3", 4]

In [2]:
import numpy as np 

In [3]:
# Create a numpy array

a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

In [4]:
# Check the type of the array

type(a)

numpy.ndarray

In [5]:
# Check the type of the values stored in numpy array

a.dtype

dtype('int64')

In [6]:
# Create numpy array

c = np.array([20, 1, 2, 3, 4])
c

array([20,  1,  2,  3,  4])

In [7]:
# Assign the first element to 100

c[0] = 100
c

array([100,   1,   2,   3,   4])

In [8]:
d = c[1:4]
d

array([1, 2, 3])

In [9]:
# Set the fourth element and fifth element to 300 and 400

c[3:5] = 300, 400
c

array([100,   1,   2, 300, 400])

In [10]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


### Numpy Statistical Functions


In [12]:
# Create a numpy array

a = np.array([1, -1, 1, -1])

In [13]:
# Get the mean of numpy array

mean = a.mean()
mean

0.0

In [14]:
# Get the standard deviation of numpy array

standard_deviation=a.std()
standard_deviation

1.0

### Plotting

In [15]:
# Plotting functions


import time 
import sys
import numpy as np 

import matplotlib.pyplot as plt
%matplotlib inline  

def Plotvec1(u, z, v):
    
    ax = plt.axes() # to generate the full window axes
    ax.arrow(0, 0, *u, head_width=0.05, color='r', head_length=0.1)# Add an arrow to the  U Axes with arrow head width 0.05, color red and arrow head length 0.1
    plt.text(*(u + 0.1), 'u')#Adds the text u to the Axes 
    
    ax.arrow(0, 0, *v, head_width=0.05, color='b', head_length=0.1)# Add an arrow to the  v Axes with arrow head width 0.05, color red and arrow head length 0.1
    plt.text(*(v + 0.1), 'v')#Adds the text v to the Axes 
    
    ax.arrow(0, 0, *z, head_width=0.05, head_length=0.1)
    plt.text(*(z + 0.1), 'z')#Adds the text z to the Axes 
    plt.ylim(-2, 2)#set the ylim to bottom(-2), top(2)
    plt.xlim(-2, 2)#set the xlim to left(-2), right(2)
